folia-supported: true
name: Fandtpa
version: 3.1
main: com.fandtpa.Main
api-version: '1.21'
commands:
  tpa:
    description: 请求传送到某个玩家
    usage: /tpa <玩家名>
  tpaccept:
    description: 接受传送请求
    usage: /tpaccept
  tpdeny:
    description: 拒绝传送请求
    usage: /tpdeny
  tpahere:
    description: 请求其他玩家传送到你这里
    usage: /tpahere <玩家名>
  rtp:
    description: 随机传送
    usage: /rtp
  home:
    description: 家的管理命令
    usage: /home <set/tp/del/list> <家名>
    aliases: [homes]
  back:
    description: 传送到上一次死亡地点
    usage: /back