folia-supported: true
name: Fandtpa
version: 1.4
main: fand.fandtpa.Main
api-version: '1.20'
commands:
  tpa:
    description: 请求传送到某个玩家
    usage: /tpa <玩家名>
  tpaccept:
    description: 接受传送请求
    usage: /tpaccept
  tpdeny:
    description: 拒绝传送请求
    usage: /tpdeny
  tpahere:
    description: 请求其他玩家传送到你这里
    usage: /tpahere <玩家名>
  home:
    description: 家的管理命令
    usage: /home <set/tp/del/list> <家名>
    aliases: [homes]
  back:
    description: 传送到上一次死亡地点
    usage: /back
  settitle:
    description: 为玩家设置称号
    usage: /settitle <玩家> <称号>
    permission: fandtpa.titles.set
    permission-message: 你没有权限使用此命令
  suicide:
    description: 自杀
  invsee:
    description: 查看其他玩家的背包
    usage: /invsee <玩家名>
    permission: fandtpa.invsee.use
  hat:
    description: 将手中的物品戴在头上
    usage: /hat
    permission: fandtpa.hat.use
  rtp:
    description: 随机传送
    usage: /rtp
    permission: fandtpa.rtp.use
  fly:
    description: 切换飞行模式
    usage: /fly
    permission: fandtpa.fly.use
  gm:
    description: 快速切换游戏模式
    usage: /gm <模式>
    permission: fandtpa.gm.use
  tab:
    description: 重新加载TAB配置
    usage: /tab reload
    permission: fandtpa.tab.reload
  speed:
    description: Set the speed of the player
    usage: /speed <fly|walk> <speed>
    aliases: [ sp ]
    permission: fandtpa.speed.use
  eco:
    description: 管理玩家经济
    usage: /eco <set|add|take> <玩家> <金额>
    permission: fandtpa.eco.use
  money:
    description: 获取玩家当前的金钱
    usage: /money
    permission: fandtpa.money.use
permissions:
  fandtpa.titles.set:
    description: 允许玩家设置称号
    default: op
  fandtpa.invsee.use:
    description: 允许查看其他玩家背包
    default: op
  fandtpa.fly.use:
    description: 允许玩家飞行
    default: op
  fandtpa.rtp.use:
    description: 允许玩家随机传送
    default: op
  fandtpa.gm.use:
    description: 快捷切换游戏模式
    default: op
  fandtpa.hat.use:
    description: 允许玩家将手中的物品戴到头上
    default: op
  fandtpa.tab.reload:
    description: 允许重新加载TAB配置
    default: op
  fandtpa.speed.use:
    description: 允许重新加载TAB配置
    default: op
  fandtpa.eco.use:
    description: 允许重新加载TAB配置
    default: op
  fandtpa.money.use:
    description: 允许重新加载TAB配置
    default: op